language: java
env:
  global:
    - DOCKER_TECENT_REGISTRY_HK=hkccr.ccs.tencentyun.com
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  # mvn build
  - mvn package -DskipTests=true -Ptest
  # docker build
  - echo ENV GIT_COMMIT=$TRAVIS_COMMIT >> Dockerfile
  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER .
  # push to docker hub
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  - docker push $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER
  # push to tecent cloud
  - docker login --username $DOCKER_TECENT_USERNAME --password $DOCKER_TECENT_PASSWORD $DOCKER_TECENT_REGISTRY_HK
  - docker tag $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER $DOCKER_TECENT_REGISTRY_HK/$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_TECENT_REGISTRY_HK/$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER
notifications:
  email:
    recipients:
      - 445172495@qq.com
      - 1479269124@qq.com
    on_success: always
    on_failure: always
